 <section id="messages">

    <?php if ($this->FlashMessenger()->render('error')): ?>
        <div id="messages" class="columns twelve alert-box alert">
            <?php echo $this->FlashMessenger()->render('error'); ?>
            <a href="" class="close">&times;</a>
        </div>
    <?php endif; ?>

    <?php if ($this->FlashMessenger()->render('success')): ?>
        <div id="messages" class="columns twelve alert-box success">
            <?php echo $this->FlashMessenger()->render('success'); ?>
            <a href="" class="close">&times;</a>
        </div>
    <?php endif; ?>

    <?php if ($this->FlashMessenger()->render('info')): ?>
        <div id="messages" class="columns twelve alert-box">
            <?php echo $this->FlashMessenger()->render('info'); ?>
            <a href="" class="close">&times;</a>
        </div>
    <?php endif; ?>

    <?php if ($this->FlashMessenger()->render('default')): ?>
        <div id="messages" class="columns twelve alert-box secondary">
            <?php echo $this->FlashMessenger()->render('default'); ?>
            <a href="" class="close">&times;</a>
        </div>
    <?php endif; ?>

</section>

<h2>Contact</h2>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('team-contact'));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formCollection($form);
echo $this->form()->closeTag($form) . PHP_EOL;
