<?php
$title = 'Delete variable';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
  <strong>'<?php echo $this->escapeHtml($variable->name); ?>'</strong>?
</p>
<?php
$url = $this->url('variable', array('action' => 'delete', 'id' => $id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int) $variable->id; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
