<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table" width="100%">
    <thead>
        <th>Title</th>
        <th>Artist</th>
        <th>
            <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add +</a>
        </th>
    </thead>
    <tbody>
        <?php foreach($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->id));?>"
                    class="label round small">Edit</a>
                <a href="<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->id));?>"
                    class="label round small alert">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
