<hr>
<footer class="columns twelve">
    <p>&copy; 2009 - <?php echo date('Y') ?> Harold Villacorte Dba Laughing Host | Denver, Colorado</p>
    <p>Powered by <a href="http://framework.zend.com/" title="Zend Framework 2."
                     target="_blank"
                     >ZF2</a> and <a href="http://foundation.zurb.com/" title="Zend Framework 2."
                            target="_blank"
                            >Foundation 3</a></p>
</footer>
