<?php $this->headTitle($this->translate('Deployment')); ?>
<h2>Deployment</h2>

<p>In addition to developing applications we also assist in deployment.  Whether you want to deploy to a cloud service, traditional lamp hosting, or to deploy as an Android app we can help.</p>

<h6>Amazon Web Services</h6>
<p>Unless you live in cave, in which case we would be very jealous of you, you have probably done business with Amazon at some point and already have an account with them so setting up on AWS would be very convenient.  In addition to providing basic cloud hosting, database services, and storage, Amazon Web Services offers some very nice app services like push notification, media transcoding, and email sending.</p>
<p>The level of services and pricing are flexible enough to serve any size application.  It can be scaled anywhere from a small personal blog on a micro instance to large scale enterprise applications.</p>

<h6>Traditional LAMP Hosting</h6>
<p>Although cloud hosting is all the rage and will probably eventually completely replace traditional hosting in the foreseeable future, traditional hosting services are still widely available and widely in use.</p>
<p>Most web based applications will be deployable on shared hosting but we recommend at the very minimum a virtual private server with full root access.  This ensures that we are able to adjust server configurations and install dependencies in a timely and efficient manner.</p>

<h6>Android</h6>
<p>Applications built using only html, css, and javascript can easily be ported to PhoneGap and deployed to mobile devices.  We currently offer support for the Android operating system.</p>
