<div class="four columns block">
    <h2><?php echo $this->translate('PHP') ?></h2>
    <ul>
        <li>Rapid Prototyping</li>
        <li>Codeigniter</li>
        <li>Zend Framework 2</li>
        <li>Drupal 7</li>
    </ul>
    <p>
        <a class="button success small ajax-link" href="<?php echo $this->url('php'); ?>">
            <?php echo $this->translate('Learn more') ?> &raquo;
        </a>
    </p>
</div>

<div class="four columns block">
    <h2><?php echo $this->translate('Javascript') ?></h2>
    <ul>
        <li>jQuery</li>
        <li>Foundation 3</li>
        <li>Phone Gap</li>
    </ul>
    <p>
        <a class="button success small ajax-link" href="<?php echo $this->url('javascript'); ?>">
            <?php echo $this->translate('Learn more') ?> &raquo;
        </a>
    </p>
</div>

<div class="four columns block">
   <h2><?php echo $this->translate('Deployment') ?></h2>
   <ul>
       <li>Amazon Web Services</li>
       <li>Traditional LAMP Hosting</li>
       <li>Android</li>
   </ul>
   <p>
        <a class="button success small ajax-link" href="<?php echo $this->url('deployment'); ?>">
            <?php echo $this->translate('Learn more') ?> &raquo;
        </a>
   </p>
</div>
