<?php $this->headTitle($this->translate('Javascript')); ?>
<h2>Javascript</h2>

<h6>jQuery</h6>
<p>jQuery is the most widely used javascript library in existence.  It takes just about every javascript function, workaround, and hack that has ever been written and consolidates them into a single javascript file that is available for any developer or designer to use.  There really is no question on whether or not to use jQuery in a project since most of the worlds computers already have the cdn version cached somewhere effectively resulting in zero overhead.  jQuery provides easy DOM traversal, effects, and so many other things but the single greatest reason to use it is for its fabulous ajax methods.  Basic ajax functionality in addition to consuming services and handling forms can be accomplished with just a few lines of code.</p>
<p>Additionally there are the jQuery UI and jQuery Mobile frameworks built on top of the core jQuery library.  They both provide rich user interfaces, effects, widgets, and themes with jQuery Mobile obviously focusing on mobile devices with touchscreens.</p>

<h6>Foundation 3</h6>
<p>This is the front end framework provided by <a href="http://zurb.com/" title="Zurb" target="_blank">Zurb</a>.  The latest version is actually Foundation 4 but we have not gotten on board with version 4 yet because of the lack of IE8 support.  Foundation is widely considered to have the most advanced responsive grid system of all the well known front end frameworks.  It also provides excellent styling for typography, buttons, navigation, and user interface elements.  And topping it all off is a series of jQuery plugins like Orbit and Magellan providing commonly used elements like content sliders and content aware navigation.</p>
<p>As a bonus Foundation optionally offers some very nice html templates, a complete set of icon fonts, off canvas layouts, and responsive tables.</p>

<h6>PhoneGap</h6>
<p>PhoneGap is a framework that provides an application container to port javascript applications to mobile devices.  It provides a standardized api to access native device systems and events with support for Andriod, iOS, BlackBerry, Windows Phone, and WebOS among a few others.</p>
<p>The PhoneGap API provides support for the following components: accelerometer, camera, capture, compass, connection, contacts, device, events, file, geolocation, globalization, in-app browser, media, notification, splashscreen, and storage.</p>
